<?php

/**
 * Dial-code countries for consultation forms.
 * Default: India (IN).
 */
return [
    'default' => 'IN',

    'list' => [
        'IN' => [
            'name' => 'India',
            'dial' => '91',
            'flag' => '🇮🇳',
            'states' => require __DIR__.'/indian_states.php',
        ],
        'US' => [
            'name' => 'United States',
            'dial' => '1',
            'flag' => '🇺🇸',
            'states' => ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington, D.C.'],
        ],
        'GB' => [
            'name' => 'United Kingdom',
            'dial' => '44',
            'flag' => '🇬🇧',
            'states' => ['England', 'Scotland', 'Wales', 'Northern Ireland'],
        ],
        'AE' => [
            'name' => 'United Arab Emirates',
            'dial' => '971',
            'flag' => '🇦🇪',
            'states' => ['Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Fujairah', 'Ras Al Khaimah', 'Umm Al Quwain'],
        ],
        'AU' => [
            'name' => 'Australia',
            'dial' => '61',
            'flag' => '🇦🇺',
            'states' => ['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania', 'Australian Capital Territory', 'Northern Territory'],
        ],
        'CA' => [
            'name' => 'Canada',
            'dial' => '1',
            'flag' => '🇨🇦',
            'states' => ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan'],
        ],
        'SG' => [
            'name' => 'Singapore',
            'dial' => '65',
            'flag' => '🇸🇬',
            'states' => ['Central Region', 'East Region', 'North Region', 'North-East Region', 'West Region'],
        ],
        'DE' => [
            'name' => 'Germany',
            'dial' => '49',
            'flag' => '🇩🇪',
            'states' => ['Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern', 'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland', 'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia'],
        ],
        'FR' => [
            'name' => 'France',
            'dial' => '33',
            'flag' => '🇫🇷',
            'states' => ['Île-de-France', 'Auvergne-Rhône-Alpes', 'Hauts-de-France', 'Nouvelle-Aquitaine', 'Occitanie', 'Provence-Alpes-Côte d\'Azur', 'Grand Est', 'Pays de la Loire', 'Brittany', 'Normandy', 'Bourgogne-Franche-Comté', 'Centre-Val de Loire', 'Corsica'],
        ],
        'NL' => [
            'name' => 'Netherlands',
            'dial' => '31',
            'flag' => '🇳🇱',
            'states' => ['Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen', 'Limburg', 'North Brabant', 'North Holland', 'Overijssel', 'South Holland', 'Utrecht', 'Zeeland'],
        ],
        'NZ' => [
            'name' => 'New Zealand',
            'dial' => '64',
            'flag' => '🇳🇿',
            'states' => ['Auckland', 'Bay of Plenty', 'Canterbury', 'Gisborne', 'Hawke\'s Bay', 'Manawatū-Whanganui', 'Marlborough', 'Nelson', 'Northland', 'Otago', 'Southland', 'Taranaki', 'Tasman', 'Waikato', 'Wellington', 'West Coast'],
        ],
        'SA' => [
            'name' => 'Saudi Arabia',
            'dial' => '966',
            'flag' => '🇸🇦',
            'states' => ['Riyadh', 'Makkah', 'Madinah', 'Eastern Province', 'Asir', 'Jazan', 'Najran', 'Tabuk', 'Hail', 'Northern Borders', 'Al Jawf', 'Al Bahah', 'Al Qassim'],
        ],
        'QA' => [
            'name' => 'Qatar',
            'dial' => '974',
            'flag' => '🇶🇦',
            'states' => ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal', 'Al Daayen', 'Al Shamal'],
        ],
        'KW' => [
            'name' => 'Kuwait',
            'dial' => '965',
            'flag' => '🇰🇼',
            'states' => ['Capital', 'Hawalli', 'Farwaniya', 'Mubarak Al-Kabeer', 'Ahmadi', 'Jahra'],
        ],
        'OM' => [
            'name' => 'Oman',
            'dial' => '968',
            'flag' => '🇴🇲',
            'states' => ['Muscat', 'Dhofar', 'Musandam', 'Al Buraimi', 'Ad Dakhiliyah', 'Al Batinah North', 'Al Batinah South', 'Ash Sharqiyah North', 'Ash Sharqiyah South', 'Ad Dhahirah', 'Al Wusta'],
        ],
        'BH' => [
            'name' => 'Bahrain',
            'dial' => '973',
            'flag' => '🇧🇭',
            'states' => ['Capital', 'Muharraq', 'Northern', 'Southern'],
        ],
        'MY' => [
            'name' => 'Malaysia',
            'dial' => '60',
            'flag' => '🇲🇾',
            'states' => ['Johor', 'Kedah', 'Kelantan', 'Malacca', 'Negeri Sembilan', 'Pahang', 'Penang', 'Perak', 'Perlis', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu', 'Kuala Lumpur', 'Labuan', 'Putrajaya'],
        ],
        'ID' => [
            'name' => 'Indonesia',
            'dial' => '62',
            'flag' => '🇮🇩',
            'states' => ['Jakarta', 'West Java', 'Central Java', 'East Java', 'Bali', 'Sumatra', 'Kalimantan', 'Sulawesi', 'Papua'],
        ],
        'PH' => [
            'name' => 'Philippines',
            'dial' => '63',
            'flag' => '🇵🇭',
            'states' => ['Metro Manila', 'Cebu', 'Davao', 'Iloilo', 'Baguio', 'Laguna', 'Cavite', 'Bulacan'],
        ],
        'TH' => [
            'name' => 'Thailand',
            'dial' => '66',
            'flag' => '🇹🇭',
            'states' => ['Bangkok', 'Chiang Mai', 'Chonburi', 'Phuket', 'Nonthaburi', 'Pathum Thani', 'Samut Prakan'],
        ],
        'JP' => [
            'name' => 'Japan',
            'dial' => '81',
            'flag' => '🇯🇵',
            'states' => ['Tokyo', 'Osaka', 'Kanagawa', 'Aichi', 'Hokkaido', 'Fukuoka', 'Kyoto', 'Hyogo', 'Saitama', 'Chiba'],
        ],
        'KR' => [
            'name' => 'South Korea',
            'dial' => '82',
            'flag' => '🇰🇷',
            'states' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Gyeonggi', 'Gangwon'],
        ],
        'CN' => [
            'name' => 'China',
            'dial' => '86',
            'flag' => '🇨🇳',
            'states' => ['Beijing', 'Shanghai', 'Guangdong', 'Zhejiang', 'Jiangsu', 'Sichuan', 'Hubei', 'Shandong'],
        ],
        'HK' => [
            'name' => 'Hong Kong',
            'dial' => '852',
            'flag' => '🇭🇰',
            'states' => ['Hong Kong Island', 'Kowloon', 'New Territories'],
        ],
        'PK' => [
            'name' => 'Pakistan',
            'dial' => '92',
            'flag' => '🇵🇰',
            'states' => ['Punjab', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan', 'Islamabad Capital Territory', 'Gilgit-Baltistan', 'Azad Kashmir'],
        ],
        'BD' => [
            'name' => 'Bangladesh',
            'dial' => '880',
            'flag' => '🇧🇩',
            'states' => ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Rangpur', 'Mymensingh'],
        ],
        'LK' => [
            'name' => 'Sri Lanka',
            'dial' => '94',
            'flag' => '🇱🇰',
            'states' => ['Western', 'Central', 'Southern', 'Northern', 'Eastern', 'North Western', 'North Central', 'Uva', 'Sabaragamuwa'],
        ],
        'NP' => [
            'name' => 'Nepal',
            'dial' => '977',
            'flag' => '🇳🇵',
            'states' => ['Bagmati', 'Gandaki', 'Lumbini', 'Karnali', 'Sudurpashchim', 'Koshi', 'Madhesh'],
        ],
        'ZA' => [
            'name' => 'South Africa',
            'dial' => '27',
            'flag' => '🇿🇦',
            'states' => ['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Limpopo', 'Mpumalanga', 'North West', 'Free State', 'Northern Cape'],
        ],
        'NG' => [
            'name' => 'Nigeria',
            'dial' => '234',
            'flag' => '🇳🇬',
            'states' => ['Lagos', 'Abuja FCT', 'Kano', 'Rivers', 'Oyo', 'Kaduna', 'Delta', 'Ogun'],
        ],
        'KE' => [
            'name' => 'Kenya',
            'dial' => '254',
            'flag' => '🇰🇪',
            'states' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Kiambu', 'Machakos'],
        ],
        'IE' => [
            'name' => 'Ireland',
            'dial' => '353',
            'flag' => '🇮🇪',
            'states' => ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kerry', 'Mayo'],
        ],
        'IT' => [
            'name' => 'Italy',
            'dial' => '39',
            'flag' => '🇮🇹',
            'states' => ['Lombardy', 'Lazio', 'Campania', 'Sicily', 'Veneto', 'Piedmont', 'Emilia-Romagna', 'Tuscany'],
        ],
        'ES' => [
            'name' => 'Spain',
            'dial' => '34',
            'flag' => '🇪🇸',
            'states' => ['Madrid', 'Catalonia', 'Andalusia', 'Valencia', 'Galicia', 'Basque Country', 'Castile and León'],
        ],
        'CH' => [
            'name' => 'Switzerland',
            'dial' => '41',
            'flag' => '🇨🇭',
            'states' => ['Zurich', 'Geneva', 'Bern', 'Vaud', 'Basel-Stadt', 'Ticino', 'St. Gallen'],
        ],
        'SE' => [
            'name' => 'Sweden',
            'dial' => '46',
            'flag' => '🇸🇪',
            'states' => ['Stockholm', 'Västra Götaland', 'Skåne', 'Uppsala', 'Östergötland'],
        ],
        'NO' => [
            'name' => 'Norway',
            'dial' => '47',
            'flag' => '🇳🇴',
            'states' => ['Oslo', 'Viken', 'Vestland', 'Trøndelag', 'Rogaland', 'Innlandet'],
        ],
        'DK' => [
            'name' => 'Denmark',
            'dial' => '45',
            'flag' => '🇩🇰',
            'states' => ['Capital Region', 'Central Denmark', 'North Denmark', 'Zealand', 'Southern Denmark'],
        ],
        'PL' => [
            'name' => 'Poland',
            'dial' => '48',
            'flag' => '🇵🇱',
            'states' => ['Masovia', 'Lesser Poland', 'Silesia', 'Greater Poland', 'Pomerania', 'Lower Silesia'],
        ],
        'BR' => [
            'name' => 'Brazil',
            'dial' => '55',
            'flag' => '🇧🇷',
            'states' => ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia', 'Paraná', 'Rio Grande do Sul', 'Pernambuco', 'Federal District'],
        ],
        'MX' => [
            'name' => 'Mexico',
            'dial' => '52',
            'flag' => '🇲🇽',
            'states' => ['Mexico City', 'Jalisco', 'Nuevo León', 'Puebla', 'Guanajuato', 'Quintana Roo', 'Yucatán'],
        ],
        'RU' => [
            'name' => 'Russia',
            'dial' => '7',
            'flag' => '🇷🇺',
            'states' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod'],
        ],
        'TR' => [
            'name' => 'Turkey',
            'dial' => '90',
            'flag' => '🇹🇷',
            'states' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Konya'],
        ],
        'EG' => [
            'name' => 'Egypt',
            'dial' => '20',
            'flag' => '🇪🇬',
            'states' => ['Cairo', 'Giza', 'Alexandria', 'Dakahlia', 'Sharqia', 'Qalyubia'],
        ],
        'IL' => [
            'name' => 'Israel',
            'dial' => '972',
            'flag' => '🇮🇱',
            'states' => ['Tel Aviv', 'Jerusalem', 'Haifa', 'Central', 'Northern', 'Southern'],
        ],
        'VN' => [
            'name' => 'Vietnam',
            'dial' => '84',
            'flag' => '🇻🇳',
            'states' => ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho'],
        ],
        'OTHER' => [
            'name' => 'Other',
            'dial' => '',
            'flag' => '🌐',
            'states' => ['Nationwide / Other'],
        ],
    ],
];
