<?php

return [
    'primary' => [
        [
            'title' => 'Start-Up',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'Business Incorporation',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Private Limited Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'LLP Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Startup India Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Sole Proprietorship Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'One Person Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Partnership Firm Registration', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'NGO',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'NGO Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Section 8 Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'FCRA Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Trust Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => '12A and 80G Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'FCRA Registration Renewal', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Compliances',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'ROC Annual Compliance for Private Limited Company', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Business Conversion',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Conversion of Pvt. Ltd. to Public Limited', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'License',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'Government License',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'MSO License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Digital Signature Certificate', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Capexil Certificate', 'url' => '#', 'type' => 'link'],
                        ['title' => 'PSARA License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'WPC ETA Certificate', 'url' => '#', 'type' => 'link'],
                        ['title' => 'MSDS Certificate', 'url' => '#', 'type' => 'link'],
                        ['title' => 'IIP UN Certificate', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Government Registration',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'EPF Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'MSME Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'ESIC Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'NSIC Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BEE Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'LMPC Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'LMPC Certificate for Import', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'ISO',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'ISO Certification', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Fssai & Eating License',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'FSSAI License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'FSSAI State License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'FSSAI Central License', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'IPR',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Copyright Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Design Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Patent Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Trademark Registration', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'CDSCO',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Drug License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'CDSCO Registration Certificate', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Tax',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'Tax Filing',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'GST Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Professional Tax Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Income Tax Return Filing', 'url' => '#', 'type' => 'link'],
                        ['title' => 'GST Refund', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Cancellation of GST Registration', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Finance & Accounts',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Accounting and Bookkeeping Services', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Virtual CFO Services', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'People Management',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Payroll Management Services', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Regulatory',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'BIS',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'ISI Mark Certification', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS CRS Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Hallmark Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'FMCS BIS Certification', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for LED Hand Lamps', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for LED Lighting Chains', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for LED Luminaires for Emergency Lighting', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for CCTV Cameras / CCTV Recorders', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for Storage Battery', 'url' => '#', 'type' => 'link'],
                        ['title' => 'BIS Registration for Trimethyl Phosphite Technical Grade', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'RBI',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'NBFC Takeover', 'url' => '#', 'type' => 'link'],
                        ['title' => 'NBFC Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Money Lending License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'NBFC Compliance', 'url' => '#', 'type' => 'link'],
                        ['title' => 'NBFC Due Diligence', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Recovery of Shares from IEPF', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Prepaid Wallet License', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'IRDAI',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'IRDA Insurance Company License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Insurance Marketing Firm IMF Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Corporate Insurance Agent License', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'SEBI',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Alternative Investment Funds (AIFs) Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Investment Adviser Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Asset Management Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'SEBI Research Analyst Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Stock Broker License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'REIT Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Foreign Portfolio Investor Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'AMFI Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Registration of Underwriters with SEBI', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Social Stock Exchange License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Merchant Banker License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Portfolio Manager Registration with SEBI', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Venture Capital Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Credit Rating Agency Registration with SEBI', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Depository Participant SEBI Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Registrar and Share Transfer Agents Registration', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Environmental',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'EIA',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Environmental Clearance', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Environmental Audit', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Environmental Compliance', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Third Party EPR Audit', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Disaster Management Plan', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Environment Management Plan', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'E-Waste Management',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'EPR Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'E-Waste Recycling Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR License for E-Waste Recyclers', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Used Electronics Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'E-Waste Recycling Plant Setup', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR Credits for E-waste Recyclers', 'url' => '#', 'type' => 'link'],
                        ['title' => 'E-waste Annual Compliance', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Used Laptop Import License', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Battery Waste Management',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Registration for Scrap Battery Import', 'url' => '#', 'type' => 'link'],
                        ['title' => 'New Battery Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Lead Acid Battery Recycling Plant Setup', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Battery Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Lead Scrap Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'New Lead Acid Battery Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'UN 38.3 Registration Certificate for Lithium Batteries', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Environmental Licensing',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Vehicle Scrapping Facility Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Used Tyre Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Metal Scrap Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR Authorization for Waste Tyres', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Vehicle Recycling Plant Setup', 'url' => '#', 'type' => 'link'],
                        ['title' => 'New Tyre Import License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Tyre Recycling Plant Setup', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Vehicle Scrapping Business in India', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Pollution NOC',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Central Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'State Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Delhi Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Uttar Pradesh Pollution Control Board (UPPCB) NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Rajasthan Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Haryana Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Maharashtra Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Gujrat Pollution Control Board NOC', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Hazardous Waste Management',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Hazardous Waste Management Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Hazardous Waste Import Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR Authorization for Waste Oil', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Solid Waste Management Authorization', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Bio-Medical Waste Recycling Plant', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Spent Catalyst Export License', 'url' => '#', 'type' => 'link'],
                    ],
                ],
                [
                    'title' => 'Plastic Waste Management',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'Plastic Waste Recycling License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR Authorization for Plastic Waste Management', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR License for Brand Owner', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Plastic Waste Export License', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR Plastic Waste Annual Compliance', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR credits for Plastic Waste Recyclers', 'url' => '#', 'type' => 'link'],
                        ['title' => 'EPR for Plastic Waste Importers', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Global',
            'url' => null,
            'type' => 'menu',
            'children' => [
                [
                    'title' => 'Global Incorporation',
                    'url' => null,
                    'type' => 'group',
                    'children' => [
                        ['title' => 'USA Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Australia Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'France Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Canada Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'New Zealand Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Qatar Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'UK Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Germany Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Dubai Company Registration', 'url' => '#', 'type' => 'link'],
                        ['title' => 'Singapore Company Registration', 'url' => '#', 'type' => 'link'],
                    ],
                ],
            ],
        ],
    ],

    'secondary' => [
        ['title' => 'About Us', 'url' => '/about-us', 'type' => 'link'],
        ['title' => 'Contact Us', 'url' => '/contact-us', 'type' => 'link'],
        ['title' => 'Blogs', 'url' => '#', 'type' => 'link'],
    ],
];
